import React, { useState } from "react";
import { ChevronDown } from "lucide-react";
import { useNavigate } from "react-router-dom";

const FaqItem = ({ number, question, answer, isOpen, onClick }) => (
  <div className="bg-white overflow-hidden">
    <button
      onClick={onClick}
      className="w-full flex items-start sm:items-center justify-between p-5 sm:p-6 md:p-8 text-left hover:bg-slate-50 transition-colors gap-3 sm:gap-4"
    >
      <span className="text-slate-800 font-bold text-base sm:text-lg md:text-xl flex items-start sm:items-center gap-2 sm:gap-4">
        <span className="text-slate-400 font-medium mt-0.5 sm:mt-0">{number}.</span>
        <span>{question}</span>
      </span>
      <ChevronDown className={`w-5 h-5 sm:w-6 sm:h-6 text-slate-400 shrink-0 mt-1 sm:mt-0 transition-transform duration-300 ${isOpen ? "rotate-180" : ""}`} />
    </button>
    <div className={`transition-all duration-300 ease-in-out ${isOpen ? "max-h-[800px] opacity-100" : "max-h-0 opacity-0"} overflow-hidden`}>
      <div className="p-5 sm:p-6 md:p-8 pt-0 text-slate-600 font-medium leading-relaxed text-sm sm:text-base md:text-lg max-w-4xl">
        {answer}
      </div>
    </div>
  </div>
);

const LandingFaq = () => {
  const [openIndex, setOpenIndex] = useState(0);
  const navigate = useNavigate();

  const faqs = [
    {
      question: "How to convert OST to PST without using Outlook?",
      answer: "The process is simple with our tool. Upload your .ost file using the box above. The cloud engine processes the file online, with no need for Outlook installed. When it gets finished, install the PST file and import it into any desktop.",
    },
    {
      question: "Is our tool the best free OST to PST converter?",
      answer: "Yes, OST to PST is free for standard file sizes. There are no extra costs, registration, or watermarks. Upgraded plans are available for priority processing and larger files, but the free service remains simple and accessible.",
    },
    {
      question: "Who uses the OST to PST Converter?",
      answer: "The tool named OST to PST converter is applied by IT administrators, businesses, and individual users of Microsoft Outlook for those who are required to access or recover emails from the OST files. This tool is useful when the Outlook profile gets deleted, and the file becomes inaccessible.",
    },
    {
      question: " How to import .ost files in Outlook?",
      answer: " To import an .ost file into Microsoft Outlook, you must convert it to a .PST file. As Outlook does not permit directly importing of the OST files. After the conversion is completed, open Outlook, visit the file, open and export it, then open the data file. After this, choose the PST file to access the emails.",
    },
    {
      question: " Is my OST file data secure while converting?",
      answer: "Yes, all file data transfers are secured with TLS 1.3 SSL encryption. The uploaded OST files and convertible PST files are automatically and permanently deleted from the servers within the duration of 2 hours of conversion. Also, we do not access, analyze, or share your email data, so that your data remains secure.",
    },
    {
      question: "Can I convert a damaged or orphaned OST file to PST?",
      answer: "Yes, our osttopst.us conversion engine has expert-grade repair algorithms for damaged OST files. It spontaneously repairs some common types of OST file damage, such as header corruption due to sudden shutdowns, folder table damage, and sync issues. Even partially damaged OST files can be successfully recovered and converted into PST files.",
    },
    {
      question: "What is the maximum OST file size that can be converted?",
      answer:"If we talk about the maximum OST file size is totally depend upon the entire data which are generated by the Outlook mailbox.",
      //answer: "The free OST PST converter manages files up to 50 GB. For enterprise mailboxes, if your file is larger than 50 GB, then our Premium plans help with larger files with priority cloud processing queues.",
    },
    {
      question: "Will the converted PST file work with my version of Outlook?",
      answer: "Yes, absolutely our free OST to PST file converter generates a Unicode-format PST compatible with Outlook 2007, 2010, 2013, 2016, 2019, 2021, and Microsoft 365. Also, the ANSI-format output for legacy Outlook 97-2003 is also accessible on request of the users.",
    },
    {
      question: "What is the difference between our free OST to PST converter and premium plans?",
      answer: "Our free tool, which is an OST to PST, covers features such as converting OST files up to 500 MB with data. If your OST file exceeds then buy our Premium plan includes features such as batch conversion, extensive file size limits, and complete support.",
    },
  ];

  return (
    <section className="bg-[#f0f9ff] pt-4 md:pt-8 pb-16 md:pb-24 px-4 md:px-6 lg:px-12">
      <div className="max-w-4xl mx-auto space-y-12 md:space-y-16">
        <div className="space-y-6 md:space-y-8">
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-center">
            Frequently Asked <span className="text-brand-500">Questions</span>
          </h2>
          
          <div className="space-y-4 mt-8">
            {faqs.map((faq, index) => (
              <div key={index} className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden hover:shadow-md transition-shadow">
                <FaqItem
                  number={index + 1}
                  question={faq.question}
                  answer={faq.answer}
                  isOpen={openIndex === index}
                  onClick={() => setOpenIndex(openIndex === index ? -1 : index)}
                />
              </div>
            ))}
          </div>
        </div>

        {/* Dark Support Banner */}
        <div className="bg-black rounded-[2rem] md:rounded-[2.5rem] p-8 sm:p-10 md:p-14 text-white space-y-6 md:space-y-8 shadow-2xl overflow-hidden relative">
          <div className="space-y-2 md:space-y-3 text-center sm:text-left">
            <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold tracking-tight text-white">
              Couldn't find what you needed?
            </h2>
            <p className="text-slate-300 text-sm sm:text-base md:text-lg font-medium">
              Submit a support ticket and we'll get back to you within 24 hours.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 pt-4">
            <button 
              className="w-full sm:w-auto bg-white text-black font-bold h-12 sm:h-14 px-8 rounded-xl sm:rounded-2xl hover:bg-slate-100 transition-all text-base sm:text-lg"
              onClick={() => navigate("/contact-us")}
            >
              Contact Support
            </button>
            <button className="w-full sm:w-auto bg-white text-black font-bold h-12 sm:h-14 px-8 rounded-xl sm:rounded-2xl hover:bg-slate-100 transition-all text-base sm:text-lg">
              Live Chat
            </button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default LandingFaq;
